name: deploy

on:
    release:
        types: [ created ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up JDK
                uses: actions/setup-java@v2
                with:
                    distribution: 'adopt'
                    java-version: '8'
                    server-id: ossrh
                    server-username: OSSRH_USERNAME
                    server-password: OSSRH_PASSWORD
                    gpg-passphrase: GPG_PASSPHRASE
                    gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

            -   name: Deploy
                run: mvn -DskipTests=true deploy
                env:
                    OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                    OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
                    GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
